### ISSUE TITLE
Issue when trying to build boot image when running on Windows

### ISSUE THREAD

**Issue by BananaEarwig** [vygr/ChrysaLisp-#2]
C:\Users\Spiri\ChrysaLisp>chrysalisp- -b ./class/lisp/boot.inc ./cmd/asm.inc

;;;;;;;;;;;;;;;;;;
; C++ ChrysaLisp ;
;;;;;;;;;;;;;;;;;;

make -j
(lambda (&optional *os* *cpu*) (setq *os* (cond (*os* *os*) (t (platform))) *cpu* (cond (*cpu* *cpu*) (t (cpu)))) (compile ((lambda () (defq *env* (env 101) *imports* (list (quote make.inc))) (catch (progn (defq func-obj (lambda (_) (cat "obj/" *os* "/" *cpu* "/" _))) (defq make-sym (lambda (_) (sym (cat "_dep_" _)))) (defq make-time (lambda (_) (defq s (sym (cat "_age_" _))) (cond ((defq G0 (def? s)) G0) (t (def *env* s (age _)))))) (within-compile-env (lambda () (include (quote sys/func.inc)) (each include (all-class-files)) (each-mergeable (lambda (_) (defq i (make-info _)) (bind (quote (d p)) i) (merge-sym *imports* d) (elem-set 1 i (map func-obj p)) (def *env* (make-sym _) i)) *imports*))) (setq *imports* (filter (lambda (_) (cond ((ge (length _) 3) (eql ".vp" (slice -4 -1 _))) (t nil))) *imports*)) (setq *imports* (filter (lambda (_) (defq d (eval (make-sym _)) p (reduce min (map make-time (elem 1 d))) d (elem 0 d)) (each-mergeable (lambda (_) (merge-sym d (elem 0 (eval (make-sym _))))) d) (some (lambda (_) (ge _ p)) (map make-time d))) *imports*)) (setq *env* nil) *imports*) (setq *env* nil)))) *os* *cpu*))

-19

**Comment by vygr** [comment]
Could this just be that the obj/ directory structure isn’t there ? At the moment there is no creation of directories done from inside ChrysaLisp.

**Comment by vygr** [comment]
So provided the 'obj/Windows/x86_64/' is present. It is in the windows branch's snapshot.zip BTW. And you have the 'arch' and 'platform' files saying 'x86_64' and 'Windows'. Then you should be able to:

./chrysalisp -b class/lisp/boot.inc cmd/asm.inc

;;;;;;;;;;;;;;;;;;
; C++ ChrysaLisp ;
;;;;;;;;;;;;;;;;;;

(make-all)
-> obj/Darwin/x86_64/class/lisp/func_pop
-> obj/Darwin/x86_64/gui/gui/statics
...
-> obj/Darwin/x86_64/gui/gui/init
-> obj/Darwin/x86_64/gui/gui/gui
-> obj/Darwin/x86_64/gui/gui/add
-> obj/Darwin/x86_64/gui/gui/update
Done
nil

(make-boot-all)
image -> obj/Windows/x86_64/sys/boot_image (176xxx)
nil

**Comment by BananaEarwig** [comment]
Thanks I will try this and let you know.

**Comment by BananaEarwig** [comment]
All working now, thanks for the help - as you may have guessed I'm not au fait with lisp :)
